# Generated by Django 6.1 on 2026-08-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Локация')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('team1', models.CharField(max_length=100, verbose_name='Команда 1')),
                ('team2', models.CharField(max_length=100, verbose_name='Команда 2')),
                ('score1', models.PositiveSmallIntegerField(default=0, verbose_name='Счёт команды 1')),
                ('score2', models.PositiveSmallIntegerField(default=0, verbose_name='Счёт команды 2')),
                ('winner', models.CharField(blank=True, help_text='Оставьте пустым для несостоявшихся матчей', max_length=100, null=True, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
